export const COMMAND_KINDS = [
  'create_confirmed_booking',
  'create_guest_booking_request',
  'confirm_guest_booking',
  'link_guest_booking_to_account',
  'request_booking_cancellation',
  'withdraw_booking_cancellation_request',
  'resolve_booking_cancellation',
  'reschedule_booking',
  'change_booking_instructor',
  'change_booking_duration',
  'change_booking_party',
  'rollback_unpaid_booking_party_additions',
  'record_booking_attendance',
  'record_course_day_attendance',
  'complete_booking',
  'record_booking_no_show',
  'create_course_enrollments',
  'transfer_course_enrollment',
  'withdraw_course_enrollment',
  'request_course_enrollment_cancellation',
  'resolve_course_enrollment_cancellation',
  'create_booking_proposal',
  'accept_booking_proposal',
  'cancel_booking_proposal',
  'expire_booking_proposal',
  'create_booking_change_request',
  'withdraw_booking_change_request',
  'resolve_booking_change_request',
  'expire_guest_reservation',
  'enforce_payment_start_gate',
  'resolve_attendance_outcome',
  'create_participant',
  'update_participant_profile',
  'assign_participant_management',
  'revoke_participant_management',
  'create_instructor_relationship',
  'revoke_instructor_relationship',
  'block_participant',
  'unblock_participant',
  'record_provider_payment_event',
  'record_manual_wallet_funding',
  'adjust_service_price',
  'record_financial_correction',
  'record_audit_correction',
  'create_course_day',
  'reassign_course_day_instructor',
] as const;

export type CommandKind = (typeof COMMAND_KINDS)[number];

export const FORBIDDEN_GENERIC_COMMAND_KINDS = [
  'setStatus',
  'updateStatus',
  'patchBooking',
  'patchEnrollment',
  'adjustWallet',
  'changeBalance',
  'setCapacity',
  'writeDocument',
  'genericMutation',
  'transitionTo',
  'patchAggregate',
] as const;

export function catalogExcludesGenericMutationCommands(): boolean {
  const catalog = new Set<string>(COMMAND_KINDS);
  return FORBIDDEN_GENERIC_COMMAND_KINDS.every((kind) => !catalog.has(kind));
}
